services:
  sveltekit:
    build: .
    ports:
      - '3000:3000'
    volumes:
      # Mount source code for development
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - VITE_USEAST_API_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - stocknear-network

networks:
  stocknear-network:
    driver: bridge 